---
title: "Report01"
output:
    html_document:
        theme: united
        keep_md: true
    params:
        argosDir: ARGOS_DIR
---


```{r loadData, echo=FALSE, include=FALSE}
source("load_data.R", local=knitr::knit_global())
data=load_data(params$argosDir)
```

## Data Clinical
```{r echo=F}
css.cell=c(
    "padding-left: .25em",
    "padding-left: 1em; padding-right: 6em;",
    "padding-left: .25em;",
    "padding-left: 1em;")
data$tbl01 %>%
    addHtmlTableStyle(align = "llll",col.rgroup=c("#FBEEC7","#FFFFFF"),css.cell=css.cell) %>%
     htmlTable(rnames=F,cnames=F,header=rep("",4))
```

## Summary
```{r echo=F}
data$summaryTbl %>% addHtmlTableStyle(align="ll",col.rgroup=c("#FFFFFF","#EBEBEB")) %>% htmlTable(rnames=F,cnames=F,header=rep("",2))
```

## Somatic alterations:

### Mutations
```{r echo=F}
data$mafTbl %>%
    addHtmlTableStyle(align="lllll",col.rgroup=c("#DBDEFF","#FFFFFF"),css.cell="padding-left: 1em;") %>%
    htmlTable(rnames=F)
```

### Copy Number - HC Events
```{r echo=F}
data$cnvTbl %>%
    addHtmlTableStyle(align="lllll",col.rgroup=c("#DEFFDB","#FFFFFF"),css.cell="padding-left: 1em;") %>%
    htmlTable(rnames=F)
```

## QC

## Copy Number - All Events
```{r echo=F}
data$cnvTblFull
```
